name: Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  wheel-linux-x86_64:
    name: Build Linux wheels (x86-64)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.10"
          channels: conda-forge
          channel-priority: strict
      - name: Install dependencies
        shell: bash -el {0}
        run: |
          conda install -c conda-forge "hdf5=1.12.2=nompi*" rust maturin gxx_linux-64
          pip install cibuildwheel
      - name: Build wheels
        shell: bash -el {0}
        run: |
          export HDF5_DIR=$CONDA_PREFIX
          export CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=$CONDA_PREFIX/bin/x86_64-conda-linux-gnu-gcc
          export RUSTFLAGS="-C linker=$CONDA_PREFIX/bin/x86_64-conda-linux-gnu-gcc"
          maturin build --release --target x86_64-unknown-linux-gnu
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-linux-x86_64
          path: target/wheels/*.whl

  wheel-macos-x86_64:
    name: Build MacOS wheels (x86-64)
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.10"
          channels: conda-forge
          channel-priority: strict
      - name: Install dependencies
        shell: bash -el {0}
        run: |
          conda install -c conda-forge "hdf5=1.12.2=nompi*" rust maturin
          pip install cibuildwheel
      - name: Build wheels
        shell: bash -el {0}
        run: |
          export HDF5_DIR=$CONDA_PREFIX
          maturin build --release
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-macos-x86_64
          path: target/wheels/*.whl

  sdist:
    runs-on: ubuntu-latest
    name: Build source distribution
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.10"
          channels: conda-forge
          channel-priority: strict
      - name: Install dependencies
        shell: bash -el {0}
        run: |
          conda install -c conda-forge "hdf5=1.12.2=nompi*" rust maturin gxx_linux-64
          pip install build
      - name: Build source distribution
        shell: bash -el {0}
        run: |
          export HDF5_DIR=$CONDA_PREFIX
          export CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=$CONDA_PREFIX/bin/x86_64-conda-linux-gnu-gcc
          export RUSTFLAGS="-C linker=$CONDA_PREFIX/bin/x86_64-conda-linux-gnu-gcc"
          maturin sdist -v
          echo "Listing target directory:"
          find target -type f -name "*.tar.gz" | sort
      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: target/wheels/*.tar.gz


