name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  wheel-linux-x86_64:
    name: Build Linux wheels (x86-64)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build manylinux wheels
        uses: pypa/cibuildwheel@v2.21.3
        env:
          CIBW_ARCHS: x86_64
          CIBW_BUILD: 'cp*-manylinux_x86_64'
        with:
          output-dir: dist
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-manylinux_x86_64
          path: dist/*

  wheel-macos-x86_64:
    name: Build MacOS wheels (x86-64)
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin
      - name: Build manylinux wheels
        uses: pypa/cibuildwheel@v2.21.3
        env:
          CIBW_ARCHS: x86_64
          CIBW_BUILD: 'cp*-macosx_x86_64'
          CIBW_ENVIRONMENT: MACOSX_DEPLOYMENT_TARGET=12.0
          CIBW_TEST_SKIP: "*"
        with:
          output-dir: dist
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-macosx_x86_64
          path: dist/*

  sdist:
    runs-on: ubuntu-latest
    name: Build source distribution
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install CI requirements
        run: python -m pip install -U build maturin
      - name: Build source distribution without vendored sources
        run: python -m build -s . -n
      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*
