name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  wheel-linux-x86_64:
    name: Build Linux wheels (x86-64)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.10
      - name: Install dependencies
        shell: bash -el {0}
        run: |
          conda install -c conda-forge hdf5 maturin
          pip install cibuildwheel
      - name: Build wheels
        shell: bash -el {0}
        run: |
          maturin build --release
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-linux-x86_64
          path: target/wheels/*.whl

  wheel-macos-x86_64:
    name: Build MacOS wheels (x86-64)
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.10
      - name: Install dependencies
        shell: bash -el {0}
        run: |
          conda install -c conda-forge hdf5 maturin
          pip install cibuildwheel
      - name: Build wheels
        shell: bash -el {0}
        run: |
          maturin build --release
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-macos-x86_64
          path: target/wheels/*.whl

  sdist:
    runs-on: ubuntu-latest
    name: Build source distribution
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.10
      - name: Install dependencies
        shell: bash -el {0}
        run: |
          conda install -c conda-forge hdf5 maturin
          pip install build
      - name: Build source distribution
        shell: bash -el {0}
        run: |
          maturin sdist
      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: target/wheels/*.tar.gz
